### PR TITLE
Fix schema publication script post-migration of the repository

### PR DESCRIPTION
**Pull request by sbesson**
Following the filtering of the specification component, the creation of the intermediate indexes was in a broken state. This commit should restore the index creation.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
I'm not sure this is the best way to fix things.  Ideally, it would be placed under `target` so it gets properly cleaned.  If we can fix the script to leave it under target, that would be preferable.

**Comment by sbesson** [comment]
@rleigh-codelibre: I can push an extra commit to move to `target`. I might have to fix the SCHEMA-release job and update the schema contributing instructions accordingly.

**Comment by rleigh-codelibre** [comment]
That would be great if it's not too much trouble.

**Comment by sbesson** [comment]
@rleigh-codelibre last commit should revert the `target/` dropping and fix all `find published` instances so that the relative links of the HTML pages should now be generated and work as expected.

**Comment by rleigh-codelibre** [comment]
This all looks fine to me and good to merge.

**Comment by sbesson** [comment]
Thanks. Merging and I'll work through a re-release of the existing schema to test the deployment job

**Pull request merged**
