### PR TITLE
Use HTTPS for Leica Microsystems URL

### PR DESCRIPTION
**Pull request by sbesson**
Attempt to fix https://ci.openmicroscopy.org/job/MODEL-merge-docs/329/

### CODE REVIEW

**Comment by sbesson** [comment]
Note that even with the change above https://ci.openmicroscopy.org/job/MODEL-merge-docs/335 is still failing with 

```
HTTPSConnectionPool(host='www.leica-microsystems.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)))
```

@manics independently confirmed the issue using `curl`:

```
$ docker run -it --rm centos curl -I https://www.leica-microsystems.com/
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html
```

and @kennethgillen reported the issue upstream. Marking this on hold while waiting for an answer/deployment fix. If needed, we can add an entry to `linkcheck_ignore` to reduce the noise.

**Comment by kennethgillen** [comment]
👍  - thanks for the noise-cancelling PR

**Comment by hflynn** [comment]
Actually, I'll see if it passes the BF job first

**Comment by hflynn** [comment]
Testing via commandline confirms this is a still an issue:

[helen@LS27174 omero (sun-links)]$ curl -I Https://leica-microsystems.com
curl: (60) SSL certificate problem: unable to get local issuer certificate

so merging

**Comment by sbesson** [comment]
Briefly retested yesterday and it seems the SSL cert issue may has been fixed upstream so we might consider reincluding this URL in the linkcheck:

```
[sbesson@ome-web-prod ~]$ curl -I https://www.leica-microsystems.com
HTTP/1.1 200 OK
Date: Thu, 11 Jan 2018 08:54:51 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Language: en
Content-Length: 93591
Cache-Control: max-age=0, public
Expires: Thu, 11 Jan 2018 08:54:51 GMT
X-UA-Compatible: IE=edge
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
```

**Comment by hflynn** [comment]
I'll open a PR to remove it from the ignore list today

**Pull request merged**
