### PR TITLE
Expand experimental model library to generate SPW samples

### PR DESCRIPTION
**Pull request by sbesson**
See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2018-November/007281.html

This builds on top of #91 to create companion OME-XML for SPW use cases.

### CODE REVIEW

**Comment by joshmoore** [comment]
Can it still create image XML? Perhaps this should be `plate.companion()` and `image.companion()`.

**Comment by sbesson** [comment]
:) I was debating between `create_{plate,image}_companion` or `create_companion(plate=plate, images=images)` but I like the idea of `Object.companion()`. In that case, would `plate.companion()` traverse the whole graph or does it stop at `ImageRef` and individual `image.companion` need to be invoked?

**Comment by joshmoore** [comment]
The latter sounds complicated. I'm fine with either of the first two signatures to start with, but I definitely need to be able to generate non SPW images.

**Comment by joshmoore** [comment]
This has been raised again by the SpaceTx crew. Do you want to get this into the first release? or shall I push the previous version to PyPI?

**Comment by sbesson** [comment]
If that is useful for others to consume, I can definitely see getting this integrated and pushed to PyPi. For 6 pre-releases, this is is where the [semver](https://semver.org/#spec-item-1) vs [PEP440](https://www.python.org/dev/peps/pep-0440/) incompatiblity might be tricky to handle - maybe `6.0.0a1` ?

**Comment by joshmoore** [comment]
Merging and looking into publishing.

**Comment by joshmoore** [comment]
https://pypi.org/project/ome-model/6.0.0a1/ -- note: alpha version downloads without `--pre` as the only version.

**Pull request merged**
