### PR TITLE
reword value domain constraint error messages

### PR DESCRIPTION
**Pull request by mtbc**
This PR simply changes the wording of some numerical exceptions' messages. My intent is to make the meaning clearer at first glance. When I first read https://www.openmicroscopy.org/qa2/qa/feedback/19174/ I was kind of nonplussed.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
I checked the C++ equivalent in `src/main/cpp/ome/xml/model/primitives/ConstrainedNumeric.h` but it's limited to `‘%1%’ not a supported value of %2%` as a catch-all.

**Comment by sbesson** [comment]
Thanks @mtbc. Looking at the exception from the description of https://github.com/openmicroscopy/bioformats/pull/3021, should we also review the wording of the `NonNegativeInteger` exceptions?

**Comment by sbesson** [comment]
Thanks. The new wording makes sense and should be suitable for a patch release of `ome-model`. What is your feeling with regard to the testing of these changes prior to bumping the version in the downstream components?

**Comment by mtbc** [comment]
No strong opinions. The changes are,

* low risk
* easy to test (just try constructing some instances)
* of no urgency.

**Comment by sbesson** [comment]
Agreed, do you want to push and extra commit to update `NEWS.md` with a summary of the changes? I will try to have a go at cutting the release today or tomorrow.

**Comment by mtbc** [comment]
I don't see a `NEWS.md`?

**Comment by sbesson** [comment]
Try to merge `origin/master` into your branch ?

**Pull request merged**
